export const demoTemplateData = [
  {
    _id: 1,
    name: "Welcome to Our Store",
    category: "General",
    lastupdated: "2025-04-25T10:30:00Z",
    status: "Active",
    message:
      "Thank you for joining our marketplace. We’re excited to have you!",
  },
  {
    _id: 2,
    name: "Order Confirmation",
    category: "Order",
    lastupdated: "2025-04-26T09:00:00Z",
    status: "Active",
    message: "Your order has been confirmed and is being processed.",
  },
  {
    _id: 3,
    name: "Payment Received",
    category: "Payment",
    lastupdated: "2025-04-24T14:20:00Z",
    status: "Active",
    message: "We have received your payment successfully. Thank you!",
  },
  {
    _id: 4,
    name: "Return Request Received",
    category: "Returns",
    lastupdated: "2025-04-23T16:00:00Z",
    status: "Draft",
    message: "We have received your return request. It is under review.",
  },
  {
    _id: 5,
    name: "Refund Processed",
    category: "Returns",
    lastupdated: "2025-04-22T11:30:00Z",
    status: "Active",
    message: "Your refund has been successfully processed.",
  },
  {
    _id: 6,
    name: "Order Shipped",
    category: "Order",
    lastupdated: "2025-04-25T12:15:00Z",
    status: "Active",
    message: "Good news! Your order has been shipped and is on its way.",
  },
  {
    _id: 7,
    name: "Order Delivered",
    category: "Order",
    lastupdated: "2025-04-26T08:00:00Z",
    status: "Active",
    message: "Your order has been delivered successfully. Enjoy your purchase!",
  },
  {
    _id: 8,
    name: "Password Reset",
    category: "General",
    lastupdated: "2025-04-21T19:45:00Z",
    status: "Draft",
    message:
      "A request to reset your password was received. Please follow the instructions.",
  },
  {
    _id: 9,
    name: "New Product Arrival",
    category: "General",
    lastupdated: "2025-04-20T13:10:00Z",
    status: "Active",
    message:
      "Check out the latest products that have just arrived in our store!",
  },
  {
    _id: 10,
    name: "Payment Failed",
    category: "Payment",
    lastupdated: "2025-04-23T07:40:00Z",
    status: "Draft",
    message: "Your recent payment attempt was unsuccessful. Please try again.",
  },
  {
    _id: 11,
    name: "Membership Renewal",
    category: "General",
    lastupdated: "2025-04-22T15:00:00Z",
    status: "Active",
    message:
      "Your membership has been successfully renewed. Thank you for staying with us!",
  },
  {
    _id: 12,
    name: "Order Cancellation Confirmed",
    category: "Order",
    lastupdated: "2025-04-24T17:30:00Z",
    status: "Draft",
    message: "Your order cancellation request has been confirmed.",
  },
];
