export const demoProductsData = [
  {
    _id: "01",
    title: "Men's Leather Jacket",
    description: "A stylish black leather jacket in excellent condition.",
    category: "Clothing",
    brand: "Zara",
    size: "L",
    condition: "Like New",
    colors: ["Black"],
    material: "Leather",
    photos: [
      "https://www.thejacketmaker.co.uk/cdn/shop/files/Mens-Legacy-Black-Leather-Biker-Jacket_1_905b5523-3a11-4dc5-9865-ad6ddf81d310.jpg?v=1739199155",
    ],
    price: 120,
    status: "Active",
  },
  {
    _id: "02",
    title: "Women's Running Shoes",
    description: "Comfortable and durable running shoes for women.",
    category: "Footwear",
    brand: "Nike",
    size: "M",
    condition: "Good",
    colors: ["Pink", "White"],
    material: "Mesh",
    photos: [
      "https://www.running-point.com/dw/image/v2/BBDP_PRD/on/demandware.static/-/Sites-master-catalog/default/dw552fd375/images/004/163/17274000_0_4.jpg?q=80&sw=2000",
    ],
    price: 45,
    status: "Blocked",
  },
  {
    _id: "03",
    title: "Analog Wrist Watch",
    description: "Classic analog wristwatch with a leather strap.",
    category: "Accessories",
    brand: "Fossil",
    size: "One Size",
    condition: "Very Good",
    colors: ["Brown", "Silver"],
    material: "Stainless Steel, Leather",
    photos: [
      "https://titanwatches.com.bd/cdn/shop/files/1584SL04_6_0f5f06b0-2bec-499f-92b3-834366b3b50d.jpg?v=1730804291&width=2000",
    ],
    price: 75,
    status: "Active",
  },
  {
    _id: "04",
    title: "Men's Formal Shirt",
    description: "White formal shirt suitable for office wear.",
    category: "Clothing",
    brand: "H&M",
    size: "M",
    condition: "Like New",
    colors: ["White"],
    material: "Cotton",
    photos: [
      "https://media.e-valy.com/cms/products/images/d309f64a-feee-4b30-8a9c-86d23330a04b",
    ],
    price: 25,
    status: "Reported",
  },
  {
    _id: "05",
    title: "Women's Handbag",
    description: "Elegant handbag with multiple compartments.",
    category: "Accessories",
    brand: "Michael Kors",
    size: "M",
    condition: "Good",
    colors: ["Beige"],
    material: "Synthetic Leather",
    photos: [
      "https://img.drz.lazcdn.com/3rd/q/aHR0cHM6Ly9wc3BrLmxvbmdwZWFuLmNvbS8xNjk2ODM3OTE4MjA2Lzk1NzYzODI3MzU4MTI3ODYwLmpwZz9pbWFnZU1vZ3IyL3RodW1ibmFpbC8xMDAweDEwMDAh_960x960q80.png_.webp",
    ],
    price: 60,
    status: "Blocked",
  },
  {
    _id: "06",
    title: "Men's Sneakers",
    description: "Casual sneakers for everyday use.",
    category: "Footwear",
    brand: "Adidas",
    size: "XL",
    condition: "Fair",
    colors: ["Blue", "White"],
    material: "Canvas",
    photos: [
      "https://media.e-valy.com/cms/products/images/3ab05b7d-5fa8-4652-ae63-413011727048",
    ],
    price: 30,
    status: "Reported",
  },
  {
    _id: "07",
    title: "Women's Winter Coat",
    description: "Warm and cozy winter coat with a hood.",
    category: "Clothing",
    brand: "Uniqlo",
    size: "S",
    condition: "Very Good",
    colors: ["Gray"],
    material: "Wool",
    photos: ["https://m.media-amazon.com/images/I/71qNZJySzdL._AC_UY1000_.jpg"],
    price: 90,
    status: "Active",
  },
  {
    _id: "08",
    title: "Men's Leather Belt",
    description: "High-quality leather belt with a silver buckle.",
    category: "Accessories",
    brand: "Tommy Hilfiger",
    size: "M",
    condition: "Like New",
    colors: ["Black"],
    material: "Leather",
    photos: [
      "https://barneysoriginals.com/wp-content/uploads/2020/09/2AJ1324.jpg",
    ],
    price: 20,
    status: "Blocked",
  },
  {
    _id: "09",
    title: "Women's Evening Dress",
    description: "Elegant evening dress perfect for formal occasions.",
    category: "Clothing",
    brand: "Forever 21",
    size: "L",
    condition: "Good",
    colors: ["Red"],
    material: "Polyester",
    photos: [
      "https://www.dhresource.com/webp/m/0x0/f2/albu/g10/M00/2B/F9/rBVaVl4K--2AD2DZAAMKJBCpp-Y560.jpg",
    ],
    price: 50,
    status: "Active",
  },
  {
    _id: "10",
    title: "Men's Sports Watch",
    description: "Durable sports watch with water resistance.",
    category: "Accessories",
    brand: "Casio",
    size: "One Size",
    condition: "Very Good",
    colors: ["Black"],
    material: "Plastic",
    photos: [
      "https://static-01.daraz.com.bd/p/95f9b7f267fbb1c041563a07bc679c75.jpg",
    ],
    price: 40,
    status: "Blocked",
  },
  {
    _id: "11",
    title: "Women's Sandals",
    description: "Comfortable sandals for casual outings.",
    category: "Footwear",
    brand: "Clarks",
    size: "S",
    condition: "Good",
    colors: ["Brown"],
    material: "Leather",
    photos: [
      "https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/266af2347a461b1d5baaa8bc4ac9986a.jpg?imageView2/2/w/500/q/60/format/webp",
    ],
    price: 25,
    status: "Active",
  },
  {
    _id: "12",
    title: "Men's Hoodie",
    description: "Cozy hoodie with a front pocket.",
    category: "Clothing",
    brand: "Champion",
    size: "XL",
    condition: "Fair",
    colors: ["Gray"],
    material: "Cotton Blend",
    photos: [
      "https://i4.cloudfable.net/styles/550x550/19.224/Black/water-polo-dad-fathers-day-father-sport-men-hoodie-20231121231908-vdsuwygk.jpg",
    ],
    price: 35,
    status: "Active",
  },
];
