export const demoReportsData = [
  {
    reportId: "R-001",
    type: "Product",
    content: "Red Nike Air Max",
    reporter: "user1@example.com",
    reason: "Fake Product",
    date: "2025-04-25T10:15:00Z",
    status: "Pending",
  },
  {
    reportId: "R-002",
    type: "User",
    content: "john.doe@example.com",
    reporter: "user2@example.com",
    reason: "Abusive Behavior",
    date: "2025-04-24T09:30:00Z",
    status: "In Review",
  },
  {
    reportId: "R-003",
    type: "Product",
    content: "Blue Leather Wallet",
    reporter: "user3@example.com",
    reason: "Wrong Category",
    date: "2025-04-23T15:20:00Z",
    status: "Resolved",
  },
  {
    reportId: "R-004",
    type: "User",
    content: "jane.smith@example.com",
    reporter: "user4@example.com",
    reason: "Spam Content",
    date: "2025-04-22T11:45:00Z",
    status: "Pending",
  },
  {
    reportId: "R-005",
    type: "Product",
    content: "Elegant Evening Dress",
    reporter: "user5@example.com",
    reason: "Inappropriate Content",
    date: "2025-04-21T18:10:00Z",
    status: "In Review",
  },
  {
    reportId: "R-006",
    type: "User",
    content: "david.lee@example.com",
    reporter: "user6@example.com",
    reason: "Fake Profile",
    date: "2025-04-20T12:00:00Z",
    status: "Resolved",
  },
  {
    reportId: "R-007",
    type: "Product",
    content: "Luxury Sunglasses",
    reporter: "user7@example.com",
    reason: "Copyright Violation",
    date: "2025-04-19T14:30:00Z",
    status: "Pending",
  },
  {
    reportId: "R-008",
    type: "User",
    content: "sophia.miller@example.com",
    reporter: "user8@example.com",
    reason: "Harassment",
    date: "2025-04-18T16:20:00Z",
    status: "Pending",
  },
  {
    reportId: "R-009",
    type: "Product",
    content: "Classic Leather Boots",
    reporter: "user9@example.com",
    reason: "Misleading Information",
    date: "2025-04-17T08:55:00Z",
    status: "In Review",
  },
  {
    reportId: "R-010",
    type: "User",
    content: "oliver.king@example.com",
    reporter: "user10@example.com",
    reason: "Account Impersonation",
    date: "2025-04-16T19:40:00Z",
    status: "Resolved",
  },
  {
    reportId: "R-011",
    type: "Product",
    content: "Summer Beach Hat",
    reporter: "user11@example.com",
    reason: "Fake Reviews",
    date: "2025-04-15T13:25:00Z",
    status: "Pending",
  },
  {
    reportId: "R-012",
    type: "Message",
    content: "This item is not as described!",
    reporter: "user12@example.com",
    reason: "Misleading Information",
    date: "2025-04-14T17:35:00Z",
    status: "In Review",
  },
];
